<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="0" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-03-17T00:22:00 IST" name="LinkedIn_Smoke" finished-at="2022-03-17T00:22:01 IST" duration-ms="1436">
    <groups>
    </groups>
    <test started-at="2022-03-17T00:22:00 IST" name="Landing Page Test" finished-at="2022-03-17T00:22:01 IST" duration-ms="1411">
      <class name="testcases.ValidateLandingPage">
        <test-method signature="testLandingPage()[pri:0, instance:testcases.ValidateLandingPage@cb191ca]" started-at="2022-03-17T00:22:00 IST" name="testLandingPage" finished-at="2022-03-17T00:22:01 IST" duration-ms="1388" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLandingPage -->
      </class> <!-- testcases.ValidateLandingPage -->
    </test> <!-- Landing Page Test -->
    <test started-at="2022-03-17T00:22:01 IST" name="Validate Login Test" finished-at="2022-03-17T00:22:01 IST" duration-ms="9">
      <class name="testcases.ValidateLogin">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.ValidateLogin@a4b2d8f]" started-at="2022-03-17T00:21:57 IST" name="setUp" finished-at="2022-03-17T00:22:00 IST" duration-ms="2843" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="doLogin(java.lang.String,java.lang.String)[pri:0, instance:testcases.ValidateLogin@a4b2d8f]" started-at="2022-03-17T00:22:01 IST" name="doLogin" data-provider="getData" finished-at="2022-03-17T00:22:01 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NegativeArraySizeException: -1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NegativeArraySizeException: -1
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:53)
at org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:153)
at org.testng.internal.Parameters.handleParameters(Parameters.java:767)
at org.testng.internal.Parameters.handleParameters(Parameters.java:704)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:70)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:49)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:904)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NegativeArraySizeException: -1
at utilities.TestUtil.getData(TestUtil.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.ValidateLogin@a4b2d8f]" started-at="2022-03-17T00:22:01 IST" name="tearDown" finished-at="2022-03-17T00:22:02 IST" duration-ms="287" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.ValidateLogin -->
    </test> <!-- Validate Login Test -->
  </suite> <!-- LinkedIn_Smoke -->
</testng-results>
